- app/build.gradle
- app/src/main/java/com/tokenbrowser/presenter/ScannerPresenter.java
You can only scan a qr code once. This created a bug when scanning an invalid qr code.
Now you can scan qr codes after an invalid qr code
- Created a Toast which only shows once every third second
- Updated com.journeyapps:zxing-android-embedded from 3.3 to 3.5
> Fixed scan issue when scanning invalid qr code

- app/src/main/res/layout/activity_chat.xml
This means words at the start of sentences will be capitalized. I would expect this to be the case for a chat app.
Fixes #316
> Set chat EditText to use textCapSentences

- app/src/main/java/com/tokenbrowser/manager/store/ConversationStore.java
- app/src/main/java/com/tokenbrowser/manager/store/PendingMessageStore.java
Partial Fix #319.
Really can't see how RealmConfig is null in these crashes so there is still an underlying issue.
This change catches the exception and logs it. There is loss of functionality if realm config is null in these situations but not enough to crash the app - needs more investigation.
> Guard against RealmConfig being null.

- app/src/main/java/com/tokenbrowser/presenter/ScannerPresenter.java
- app/src/main/java/com/tokenbrowser/util/QrCode.java
- app/src/main/java/com/tokenbrowser/util/QrCodeHandler.java
- app/src/main/java/com/tokenbrowser/util/QrCodeType.java
- app/src/main/res/values/strings.xml
Related to this PR: https://github.com/tokenbrowser/token-android-client/pull/315
Made it possible to scan a payment address. This was suppose to be merged into the `external-payment` branch, but forgot about it.
> Added the option to scan an payment address

- app/src/main/java/com/tokenbrowser/util/QrCode.java
- app/src/main/java/com/tokenbrowser/util/QrCodeHandler.java
- app/src/main/java/com/tokenbrowser/util/QrCodeType.java
When an external qr code was scanned, the wrong qr code type was returned.
Also guarding against empty query params
Related to this fabric crash https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/590224eebe077a4dccff7b81?time=last-thirty-days
> Returned wrong qr code type

- app/src/main/java/com/tokenbrowser/model/network/App.java
App crashed because `reputation_score` was null
Related: https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/590228c1be077a4dccffa3d7?time=last-thirty-days
> Check if reputation_score equals null

- app/src/main/java/com/tokenbrowser/presenter/ImageConfirmationPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ImageCropPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/FileUtil.java
- app/src/main/res/values/strings.xml
I discovered some IO work called on the main thread. These methods now returns a `Single` which runs on a worker thread.
In the second commit, I basically rewrote most of the ImageConfirmationPresenter. Before, it created a new file every time `initShortLivingObjects` was called. This was a bad solution. Now, we show the image and create a new file if the user approve.
> Io cleanup

- app/src/main/java/com/tokenbrowser/model/local/UnsignedW3Transaction.java
- app/src/main/java/com/tokenbrowser/model/sofa/SofaAdapters.java
- app/src/main/java/com/tokenbrowser/presenter/PaymentRequestConfirmPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
- app/src/main/java/com/tokenbrowser/util/QrCodeHandler.java
- app/src/main/java/com/tokenbrowser/view/fragment/DialogFragment/PaymentConfirmationDialog.java
- app/src/main/java/com/tokenbrowser/view/fragment/DialogFragment/WebPaymentConfirmationListener.java
We do this the more "standard" way so we pass the signed transaction back to the webview for broadcasting to blockchain.
> WIP: Show confirmation dialog when signing transaction.

- app/src/main/java/com/tokenbrowser/presenter/webview/SOFAHost.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaHostListener.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaHostWrapper.java
- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
Nothing really changed here. I just pulled the part into seperate classes.
There is a little bit "too much" abstraction going on here. `SOFAHost` is communicating with `SofaHostWrapper` via a `SofaHostListener`.
There is a reason for this -- `SOFAHost` will be injected into the webview and when it is, it is vulnerable to being attacked from javascript on that webpage. Therefore we want as little code as possible in the injected object.
> Webview cleanup

- app/src/main/java/com/tokenbrowser/crypto/ECKey.java
- app/src/main/java/com/tokenbrowser/crypto/util/ByteUtil.java
- app/src/test/java/com/tokenbrowser/crypto/util/ByteUtilTest.java
if either r or s don't fill out 32 bytes the signature generated ends up too short and is invalid.
> fix signature length when either r or s do not fill 32 bytes

- app/src/main/java/com/tokenbrowser/manager/BalanceManager.java
- app/src/main/java/com/tokenbrowser/manager/TokenManager.java
- app/src/main/java/com/tokenbrowser/manager/network/EthereumInterface.java
- app/src/main/java/com/tokenbrowser/manager/network/interceptor/SigningInterceptor.java
- app/src/main/java/com/tokenbrowser/model/network/GcmDeregistration.java
- app/src/main/java/com/tokenbrowser/presenter/SignOutPresenter.java
Block the deletion of local data until the web calls are done.
If the web calls fail we will still delete local data, the web will be in an invalid state but so be it.
Ensuring that when deregistering from ETH GCMs that we delete all addresses, just just the local one.
Tested and works, but might be some edge cases.
> Ensure signout works

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
Clicking "Pay" in Chat, was causing the UI to render as if it were "requesting" ETH.
It has been this way ever since it was added: https://github.com/tokenbrowser/token-android-client/commit/2837840#diff-b6e7a6a1ca0205a4e76c27f5fcc31c8cR265
Which seems odd. It looks like changing this will only have UI consequences, but it it hard to be certain.
> Set correct payment type in UI

- app/src/main/java/com/tokenbrowser/crypto/signal/store/SignalIdentityKeyStore.java
- app/src/main/java/com/tokenbrowser/manager/TokenManager.java
- app/src/main/java/com/tokenbrowser/manager/UserManager.java
- app/src/main/java/com/tokenbrowser/manager/store/BlockedUserStore.java
- app/src/main/java/com/tokenbrowser/manager/store/ContactStore.java
- app/src/main/java/com/tokenbrowser/manager/store/ConversationStore.java
- app/src/main/java/com/tokenbrowser/manager/store/PendingMessageStore.java
- app/src/main/java/com/tokenbrowser/manager/store/PendingTransactionStore.java
- app/src/main/java/com/tokenbrowser/manager/store/UserStore.java
- app/src/main/java/com/tokenbrowser/presenter/ViewAppPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewUserPresenter.java
- app/src/main/java/com/tokenbrowser/view/BaseApplication.java
The app crashes when opening it after the OS has wiped its memory. This is because the `Application` (and `ApplicationContext`) are destroyed.
Most things (everything under `TokenManager`) are recreated when a new `Application` is constructed. Realm isn't initialised again though as that is triggered through `SplashPresenter` and the OS won't route you through the splash screen when reviving an app (it'll just load up the last view you were in).
To fix this, I ensure Realm is always initialised when a new `Application` is initialised. See the first commit for more info.
This leaves us in the awkward situation that calls to Realm may be done before Realm is even intialised. The second commit addresses this by blocking access to Realm until Realm is initialised. Blocking calls aren't …
> Fixes for surviving reviving a dead app

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/view/adapter/MessageAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentRequestViewHolder.java
This is a result of using shaky logic to correctly render things.
When decided if something was sent by a remote user or not it is a bad idea to determine that by looking at the contents of the message -- instead, you should just actually find out who sent the message.
There was unfortunately a bug meaning that incoming messages were not being marked as incoming messages. I have fixed that. I had to add a workaround to ensure existing payment requests continued to be rendered correctly -- I have timestamped this fix so that it can be safely removed in the future.
> Correctly render payment requests

- app/src/main/java/com/tokenbrowser/crypto/HDWallet.java
- app/src/main/java/com/tokenbrowser/manager/UserManager.java
- app/src/main/java/com/tokenbrowser/util/SharedPrefsUtil.java
Fixes #414 
When creating a new wallet the incorrect path was being used to derive payment address.
When opening the app a second time the correct path would be derived, but the old, incorrect address had already been registered on the backend.
This change fixes the original path derivation bug, and then triggers the client to reregister with the backend.
> HD wallet path derivation bug

- app/src/main/java/com/tokenbrowser/presenter/BackupPhraseInfoPresenter.java
Bug: You could click the continue button without clicking the checkbox
> Make continue button unclickable on init

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/UserManager.java
- app/src/main/java/com/tokenbrowser/manager/network/IdInterface.java
- app/src/main/java/com/tokenbrowser/presenter/PaymentRequestConfirmPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewAppPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewUserPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/QrCodeHandler.java
When clicking a username in chat it would do a query; which is incorrect. The username is known so it should just do a lookup for that exact username.
This triggered a big refactor because other places were incorrectly searching instead of just looking up the username correctly.
> Refactor username search endpoints

- app/src/main/java/com/tokenbrowser/presenter/UserSearchPresenter.java
Until it is ready for release. @martintoften you need to be aware of this when adding UI components for group chat. We want to merge to `master` often, but, `master` has to be shippable at all times.
> Hide group UI in release builds.

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/model/local/Group.java
- app/src/main/java/com/tokenbrowser/presenter/GroupSetupPresenter.java
- app/src/main/java/com/tokenbrowser/view/adapter/GroupParticipantAdapter.java
- app/src/test/java/com/tokenbrowser/model/local/GroupTest.java
Very much WIP but not a problem to merge this.
Connects the UI to Signal. A group is created and send to the participants. A client being added to a group will currently ignore it.
> Allow for the creation of groups in Signal

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/chat/SofaMessageReceiver.java
No functional changes. Just pulling code out of `SofaMessageManager`.
This time all the message receiving code has been moved to its own class. This will make it easier to add "group" specific logic without growing a god class. There is still some room for refactoring here but this is a step in the right direction.
> Refactor: Move message receiving code into seperate class

- app/src/main/java/com/toshi/manager/TransactionManager.java
- app/src/main/java/com/toshi/view/notification/ChatNotificationManager.java
- app/src/main/java/com/toshi/view/notification/ExternalPaymentNotificationManager.java
- app/src/main/java/com/toshi/view/notification/ToshiNotificationBuilder.java
- app/src/main/java/com/toshi/view/notification/model/ChatNotification.java
- app/src/main/java/com/toshi/view/notification/model/ExternalPaymentFailedNotification.java
- app/src/main/java/com/toshi/view/notification/model/ToshiNotification.java
- app/src/main/res/values/strings.xml
Related https://github.com/toshiapp/toshi-android-client/issues/561
I made a new manager for managing external payment notifications. It was weird to use the `ChatNotificationManager` to show info about an external payment. The content of the notification was also wrong.
> Notifications

- app/src/main/res/layout/list_item__request_remote.xml
Put positive action on right because the positive action is on the right in android dialogs.
> Reverse button order on payment requests

- app/src/main/java/com/toshi/extensions/SofaMessageExtensions.kt
- app/src/main/java/com/toshi/manager/store/ConversationStore.java
- app/src/main/java/com/toshi/viewModel/MainViewModel.kt
We don't want to disturb the user with status messages. 
In this PR I filter out all status messages in `MainViewModel`. This prevents the red dot on the nav bar to update. I also don't update the unread counter if `SofaMessage` is of status message type in `ConversationStore`
> Mute status message alerts

- app/build.gradle
- app/src/main/res/drawable/circle_border.xml
- app/src/main/res/layout/list_item__recent.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
I'd actually been thinking about using a `ConstraintLayout` for this before, and it made setting up the divider a LOT easier. 
Also TIL that `android:foreground` exists, which made my life a lot easier.
> Chat refactor, pt 3: Convert to ConstraintLayout, fix design nits
