- app/src/main/java/com/tokenbrowser/presenter/DepositPresenter.java
- app/src/main/res/values/strings.xml
The copy to clipboard value was wrong. Changed from token_id to payment_address
> Now copying the payment address

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/TransactionManager.java
- app/src/main/java/com/tokenbrowser/manager/UserManager.java
- app/src/main/java/com/tokenbrowser/presenter/DepositPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/FileUtil.java
- app/src/main/java/com/tokenbrowser/util/ImageUtil.java
- app/src/main/java/com/tokenbrowser/view/custom/DragAndDropView.java
Each commit is small and self-contained. Mostly just guarding against exceptions.
> Various fixes reported in Crashlytics

- app/src/main/java/com/tokenbrowser/manager/TransactionManager.java
- app/src/main/java/com/tokenbrowser/model/sofa/Payment.java
- app/src/main/java/com/tokenbrowser/model/sofa/SofaType.java
- app/src/main/java/com/tokenbrowser/presenter/DepositPresenter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/TransactionViewHolder.java
Just review my change. Your changes are fine to merge,
> Fabric fixes

- app/src/main/java/com/tokenbrowser/presenter/DepositPresenter.java
- app/src/main/java/com/tokenbrowser/util/QrCode.java
- app/src/main/java/com/tokenbrowser/util/SharedPrefsUtil.java
The qr code was generated from token_id, not payment_address
> Qr code deposit view fix

- app/src/main/java/com/tokenbrowser/model/sofa/Payment.java
- app/src/main/java/com/tokenbrowser/model/sofa/PaymentRequest.java
- app/src/main/java/com/tokenbrowser/view/adapter/RecentAdapter.java
- app/src/main/res/values/strings.xml
Issue: The message shown in the conversation list always showed a successful payment message
> Payment message shown in conversation list fix

- app/src/main/java/com/tokenbrowser/presenter/EditProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/SettingsPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewAppPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ViewUserPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/ImageUtil.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/AppListViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/ContactViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/ConversationViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentRequestViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/RecommendedAppsViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/SearchAppViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/TextViewHolder.java
- app/src/main/java/com/tokenbrowser/view/fragment/DialogFragment/PaymentRequestConfirmationDialog.java
"downloadOnly" feature of Glide was being used, this uses the Glide cache.
Rewrote the code to achieve the same but completely bypassing the Glide cache.
> Fix issue with image caching when profile editing

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
It can happen in some edge cases, resulting in messages being rendered twice.
> Bug: Explicitly block double message subscription

- app/src/main/java/com/tokenbrowser/manager/TokenManager.java
- app/src/main/java/com/tokenbrowser/manager/store/TokenMigration.java
There's still the possibility for managers to be initialised twice which is unfortunate but won't currently crash.
> Bug: Avoid Realm being initialised twice

- app/src/main/java/com/tokenbrowser/manager/TransactionManager.java
- app/src/main/java/com/tokenbrowser/manager/model/PaymentTask.java
Refactor transaction processing to be more reactive. Ideally I'd like to pull some of this transaction processing code into seperate classes.
> Refactor: TransactionManager

- app/src/main/res/layout/activity_deposit.xml
- app/src/main/res/values/strings.xml
> Extra warning about us running on Testnet.

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tokenbrowser/presenter/EditProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ImageConfirmationPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ImageCropPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/factory/ImageCropPresenterFactory.java
- app/src/main/java/com/tokenbrowser/util/FileUtil.java
- app/src/main/java/com/tokenbrowser/view/activity/ImageCropActivity.java
- app/src/main/res/drawable/ic_clear.xml
- app/src/main/res/layout/activity_image_crop.xml
- app/src/main/res/layout/activity_sign_in.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Added ImageCropActivity, which takes care of the cropping and uploading
I have issues with the avatar caching when returning back to the EditProfileActivity. Check out the last commit to see if you agree with the solution. It's a bit hacky
> Avatar crop functionality

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/UserManager.java
- app/src/main/java/com/tokenbrowser/manager/store/BlockedUserStore.java
- app/src/main/java/com/tokenbrowser/manager/store/TokenMigration.java
- app/src/main/java/com/tokenbrowser/model/local/BlockedUser.java
- app/src/main/java/com/tokenbrowser/presenter/ViewUserPresenter.java
- app/src/main/java/com/tokenbrowser/service/GcmMessageReceiver.java
- app/src/main/java/com/tokenbrowser/util/DialogUtil.java
- app/src/main/java/com/tokenbrowser/util/UserBlockingHandler.java
- app/src/main/java/com/tokenbrowser/view/activity/ViewUserActivity.java
- app/src/main/res/layout/activity_user_profile.xml
- app/src/main/res/menu/profile.xml
- app/src/main/res/values/strings.xml
Adds the option to block users. 
You can still send messages to the blocked user. Should this be possible?
You can also view a blocked user's profile. Should this be possible?
> Block users

- app/src/main/java/com/tokenbrowser/presenter/ViewUserPresenter.java
- app/src/main/java/com/tokenbrowser/util/UserBlockingHandler.java
- app/src/main/java/com/tokenbrowser/view/activity/ViewUserActivity.java
onViewAttached could be called before the menu was created, so if this happens and the user is blocked, it will show it as unblocked in the options menu
> Fix a block user bug

- app/build.gradle
- app/src/main/java/com/tokenbrowser/presenter/MainPresenter.java
- app/src/main/res/values/colors.xml
Forked the navigation library because they haven't merged the PR.
The design has different colors for inactive state
> Add different colors to bottom navigation

- app/src/debug/res/values/urls.xml
- app/src/main/java/com/tokenbrowser/presenter/AppsPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaInjector.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaWebViewClient.java
- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
- app/src/main/java/com/tokenbrowser/view/adapter/SearchAppAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/SearchAppDappViewHolder.java
- app/src/main/res/layout/fragment_apps.xml
- app/src/main/res/values/strings.xml
- app/src/release/res/values/urls.xml
Various improvements (see each commit for more details).
> Lots of smaller webview improvements

- app/src/main/java/com/tokenbrowser/presenter/ContactsPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/RecentPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/UserSearchPresenter.java
- app/src/main/java/com/tokenbrowser/util/UserSearchType.java
- app/src/main/java/com/tokenbrowser/view/activity/UserSearchActivity.java
- app/src/main/java/com/tokenbrowser/view/fragment/toplevel/RecentFragment.java
- app/src/main/res/drawable/ic_add_white.xml
- app/src/main/res/layout/activity_scanner.xml
- app/src/main/res/layout/activity_user_search.xml
- app/src/main/res/layout/fragment_recent.xml
- app/src/main/res/menu/recent.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
1. commit: Added a textview to the scan view
2. commit: Removed all the action from recent view and added a new add icon(Redirecting in next commit)
3. commit: Made the UserSearch view more flexible. Also updated the ui.
If you open the UserSearch view from profile, the profile will appear if you click an user
If you open the UserSearch view from recent, the chat will appear if you click an user
> Small ui updates

- app/src/main/java/com/tokenbrowser/presenter/webview/SofaInjector.java
- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
Two small commits, both explain themselves
> Small dapp fixes

- app/src/main/java/com/tokenbrowser/view/custom/RoundCornersImageView.java
- app/src/main/res/drawable/frame.xml
- app/src/main/res/layout/list_item__image_message_local.xml
- app/src/main/res/values-w400dp/dimens.xml
- app/src/main/res/values-w450dp/dimens.xml
- app/src/main/res/values/dimens.xml
Better, but still some issues.
> Use LayerDrawable to render frame over image

- app/src/main/java/com/tokenbrowser/util/CurrencyUtil.java
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/59167b4cbe077a4dcca86371?time=last-thirty-days
> Catch exception if currency code isn't found

- app/src/main/java/com/tokenbrowser/presenter/EditProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
Wait until the conversation is loaded to send media messages
If the message is sent before the conversation is loaded, the image will not be displayed
> Sending media bug

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/view/custom/ChatInputView.java
- app/src/main/res/drawable/background_input_chat.xml
- app/src/main/res/drawable/ic_photo.xml
- app/src/main/res/drawable/ic_send.xml
- app/src/main/res/layout/activity_chat.xml
- app/src/main/res/layout/view_chat_input.xml
- Moved the input view into a custom view. 
- Updated the layout
- Added animations for hiding/showing the send button
> Chat input view

- app/src/main/java/com/tokenbrowser/manager/BalanceManager.java
- app/src/main/java/com/tokenbrowser/model/network/Currency.java
- app/src/main/java/com/tokenbrowser/presenter/AmountPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/CurrencyPresenter.java
- app/src/main/java/com/tokenbrowser/util/CurrencyComparator.java
- app/src/main/java/com/tokenbrowser/util/CurrencyUtil.java
- app/src/main/res/layout/activity_amount.xml
- Sorting currencies by name and adding the most common currencies to the top of the list.
- Also changing the format of currencies. `<Currency Symbol><Amount><Currency code> <eth amount> <eth symbol>`
> Currency improvements

- app/src/main/java/com/tokenbrowser/util/SharedPrefsUtil.java
Clear currency data from shared preferences
> Clear currency data

- app/src/main/java/com/tokenbrowser/presenter/SignOutPresenter.java
If gcm unregister finished successful, the user data wasn't cleared
> Sign out fix

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/TransactionManager.java
- app/src/main/java/com/tokenbrowser/manager/model/SofaMessageTask.java
- app/src/main/java/com/tokenbrowser/manager/network/EthereumService.java
- app/src/main/java/com/tokenbrowser/manager/store/ConversationStore.java
- app/src/main/java/com/tokenbrowser/manager/store/PendingMessageStore.java
- app/src/main/java/com/tokenbrowser/model/local/Conversation.java
- app/src/main/java/com/tokenbrowser/model/local/PendingMessage.java
- app/src/main/java/com/tokenbrowser/model/local/PendingTransaction.java
- app/src/main/java/com/tokenbrowser/model/sofa/OutgoingAttachment.java
- app/src/main/java/com/tokenbrowser/model/sofa/SofaMessage.java
- app/src/main/java/com/tokenbrowser/model/sofa/SofaType.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/OutgoingMessageQueue.java
- app/src/main/java/com/tokenbrowser/presenter/chat/PendingTransactionsObservable.java
- app/src/main/java/com/tokenbrowser/service/GcmMessageReceiver.java
- app/src/main/java/com/tokenbrowser/view/adapter/MessageAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/RecentAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/TimestampMessageViewHolder.java
- app/src/main/java/com/tokenbrowser/view/notification/ChatNotificationManager.java
- app/src/main/res/layout/list_item__timestamp.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Added a timstamp message in the chat view
> Chat timestamp message

- app/src/main/java/com/tokenbrowser/view/adapter/MessageAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentRequestViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/PaymentViewHolder.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/TextViewHolder.java
- app/src/main/res/layout/list_item__payment.xml
- app/src/main/res/layout/list_item__request_local.xml
- app/src/main/res/layout/list_item__text_message_local.xml
- app/src/main/res/values/strings.xml
Error states for payments, payments request and regular messages
> Chat error states

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/res/values/dimens.xml
> Add extra top  padding

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/view/custom/ChatInputView.java
- app/src/main/res/layout/view_chat_input.xml
> Update the chat input view

- app/src/main/java/com/tokenbrowser/manager/TransactionManager.java
- app/src/main/java/com/tokenbrowser/model/network/SignedTransaction.java
- app/src/main/java/com/tokenbrowser/model/network/TransactionRequest.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaHostWrapper.java
Take an unsignedW3Transaction, pass it to the backend to create a skeleton, sign the skeleton.
> Generate skeleton for signing from web apps

- app/src/main/res/layout/activity_chat.xml
- app/src/main/res/layout/view_chat_input.xml
> Make chat input TextView grow over several lines

- app/src/main/res/layout/list_item__contact.xml
- app/src/main/res/layout/list_item__recent.xml
- app/src/main/res/layout/list_item__search_app.xml
> Update the list items to match design

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/view/adapter/ContactsAdapter.java
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/592b2309be077a4dcc5bfb72?time=last-ninety-days
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/592dcf31be077a4dcc72639b?time=last-ninety-days
> Various fabric fixes

- app/src/main/java/com/tokenbrowser/presenter/MainPresenter.java
Show a notification alert icon on the me tab if the user hasn't backed up the backup phrase
> Notify that the user hasn't backed up the backup phrase

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/TokenManager.java
Two fixes here.
Don't init managers twice in TokenManager (it's unneccesary)
If attachSubscribers is run twice, handle it gracefully.
> Don't double subscribe in SofaMessageManager.

- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/TokenManager.java
- app/src/main/java/com/tokenbrowser/manager/store/ContactThreadStore.java
- app/src/main/java/com/tokenbrowser/manager/store/TokenMigration.java
- app/src/main/java/com/tokenbrowser/model/local/ContactThread.java
- app/src/main/java/com/tokenbrowser/presenter/MainPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/RecentPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/UserSearchType.java
- app/src/main/java/com/tokenbrowser/view/adapter/MessageAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/RecentAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/ThreadViewHolder.java
- app/src/main/java/com/tokenbrowser/view/notification/ChatNotificationManager.java
- app/src/main/res/menu/recent.xml
- app/src/main/res/values/strings.xml
This naming convention comes directly from Signal, so it makes sense to match their naming convention.
Eventually "GroupThread" will be added -- which will support group chat.
> Rename "Conversation" to "ContactThread"

- app/src/main/java/com/tokenbrowser/service/GcmMessageReceiver.java
If `getUserFromPaymentAddress(...)` returns nothing, handle the message as an external payment instead of logging an error
> Handle external payments

- app/src/main/java/com/tokenbrowser/crypto/signal/ChatService.java
- app/src/main/java/com/tokenbrowser/crypto/signal/network/ChatInterface.java
- app/src/main/java/com/tokenbrowser/manager/SofaMessageManager.java
- app/src/main/java/com/tokenbrowser/manager/chat/SofaMessageRegistration.java
- app/src/main/java/com/tokenbrowser/manager/model/SofaMessageTask.java
Two unrelated commits 🙈
I got distracted and decided to refactor some code out of SofaMessageManager in preparation of me adding group chat support.
> Refactor in preparation for group chat

- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
Go back try previous website if available instead of killing the activity when clicking on the back button
> Handle back button in the webview

- app/src/main/java/com/tokenbrowser/exception/CurrencyException.java
- app/src/main/java/com/tokenbrowser/manager/BalanceManager.java
- app/src/main/java/com/tokenbrowser/presenter/AmountPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/EditProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/RecentPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/ScannerPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/webview/SofaHostWrapper.java
- app/src/main/java/com/tokenbrowser/presenter/webview/WebViewPresenter.java
- app/src/main/java/com/tokenbrowser/util/CurrencyUtil.java
- app/src/main/java/com/tokenbrowser/util/FileUtil.java
- app/src/main/java/com/tokenbrowser/util/SharedPrefsUtil.java
- app/src/main/java/com/tokenbrowser/view/adapter/SettingsAdapter.java
- app/src/main/res/values/strings.xml
1 . commit issue: 
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/59317023be077a4dcc9425d2?time=last-ninety-days
2 . commit issue:
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/5922605ebe077a4dcc0d0642?time=last-ninety-days
3 . commit issue:
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/5927365ebe077a4dcc3ae0b7?time=last-ninety-days
4 . commit issue:
Anders showed me a bug where the scanner view didn't work as expected when rotating the screen.
6 . commit issue:
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/59370408be077a4dccc49439?time=last-ninety-days
7 . commit issue:
https://fabric.io/bakken--bck2/android/apps/com.tokenbrowser/issues/593a8997be077a4dcce52084?time=last-ninety-days
8 . commit issue: …
> Various fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/tokenbrowser/presenter/GroupParticipantsPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/UserSearchPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/factory/GroupParticipantsPresenterFactory.java
- app/src/main/java/com/tokenbrowser/view/activity/GroupParticipantsActivity.java
- app/src/main/java/com/tokenbrowser/view/adapter/GroupParticipantAdapter.java
- app/src/main/java/com/tokenbrowser/view/adapter/viewholder/GroupParticipantViewHolder.java
- app/src/main/res/drawable/ic_add.xml
- app/src/main/res/layout/activity_group_participants.xml
- app/src/main/res/layout/activity_user_search.xml
- app/src/main/res/layout/list_item__group_participant.xml
- app/src/main/res/values/strings.xml
> Group chat ui

- app/src/main/java/com/tokenbrowser/presenter/UserSearchPresenter.java
> Import correct dependency

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
Caused by logic that needed negating.
> Fix keyboard hide issue

- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
Scroll conversation to last known position, rather than bottom.
> Handle config change in chat.

- app/src/main/java/com/tokenbrowser/presenter/EditProfilePresenter.java
- app/src/main/java/com/tokenbrowser/presenter/GroupSetupPresenter.java
- app/src/main/java/com/tokenbrowser/presenter/chat/ChatPresenter.java
- app/src/main/java/com/tokenbrowser/util/PermissionUtil.java
- app/src/main/java/com/tokenbrowser/view/activity/ChatActivity.java
- app/src/main/java/com/tokenbrowser/view/activity/EditProfileActivity.java
Improved the permission handling a bit. What do you think?
> Refactor permission handling

- app/src/main/java/com/toshi/view/custom/PassphraseInputView.java
Related https://fabric.io/bakken--bck2/android/apps/org.toshi/issues/59c45d41be077a4dcc06bc29?time=last-seven-days
> Guard against NPE

- app/src/main/java/com/toshi/manager/store/ConversationStore.java
Add missing `subscribeOn` calls when creating any kind of Rx observable. I removed some calls because they are now being added earlier on and there is no need for double `subscribeOn` calls.
> Ensure all conversation operations are done on same thread

- app/src/main/java/com/toshi/view/activity/ViewDappActivity.kt
- app/src/main/java/com/toshi/view/custom/DappHeaderView.kt
- app/src/main/res/layout/view_dapp_header.xml
Only enable collapsing when we have a cover image
> Collapse header if no cover image

- app/src/main/java/com/toshi/presenter/BackupPhraseVerifyPresenter.java
- app/src/main/java/com/toshi/view/activity/GroupInfoActivity.kt
- app/src/main/java/com/toshi/view/activity/LandingActivity.kt
- app/src/main/java/com/toshi/view/activity/MainActivity.kt
- app/src/main/java/com/toshi/view/notification/model/ChatNotification.java
Fixed a bug where tab 4 was selected after backing up the passphrase
> Create constants for navigation tabs
